### ISSUE TITLE
gondolaweb.com is down

### ISSUE THREAD

**Issue by jmhodges** [rainycape/gondola#14]
http://gondolaweb.com is currently returning a default nginx page.

Screenshot below.

![screen shot 2016-11-15 at 4 14 06 pm](https://cloud.githubusercontent.com/assets/598/20329667/8cbb1138-ab4e-11e6-8d87-40d55d40f1eb.png)

**Comment by fiam** [comment]
@jmhodges  thanks for the heads up. I had moved the site to a different machine but I failed update the nginx config properly. It should be fixed now.
